metabologram_out_dir : "~/toy0/analys01/results/plots/"


## DEG infos
dir_deg : "~/toy0/analys01/metabologram_data/DEG_tables/"
DEG_tables:
  1 : "DEG_random.tsv"
  2 : "DEG_random.tsv"
  
columns_deg : ['external_gene_name', 'log2FoldChange']



## DAM infos
dir_dam : "~/toy0/analys01/metabologram_data/DAM_tables/"
DAM_tables:   # fill here 1: 2: etc
  1 : simulfractions--in--toy0-b_a-KW.tsv 
  2 : simulfractions--in--toy0-a_b-KW.tsv
 
columns_dam : ['metabolite', 'log2FC']  


# titles by comparison
titles:
  1: "b vs a"
  2: "a vs b"
  
  
# pathways files, both done by you. The one of metabolites has the names as in your DAM table
pathways_files:
  genes : "~/toy0/analys01/metabologram_data/pathways_genes_list_modified.tsv"
  metabolites : "~/toy0/analys01/metabologram_data/pathways_metabolites.tsv"

