# This is toy2 configuration file example
# Note: for indentation use space (never tab!), 2-space indents
# coments start with #

# -----------------------------
# necesary to all steps
# -----------------------------

metadata_path : ~/toy2/data/metadata_toy2.csv
targetedMetabo_path: ~/toy2/data/metabo_toy2.xlsx
amountMaterial_path : null # null or the file name, if available, in data/
typeprep : VIBMEC_output_prep

name_abundance : rawAbundances
name_meanE_or_fracContrib : FracContribution_C
name_isotopologue_prop : CorrectedIsotopologues # isotopologue proportions
name_isotopologue_abs : null  # isotopologue absolute values (for toy2 not avail)

conditions : 
 - Control # first must be control
 - L-Cycloserine 
suffix : toy2a001
out_path : ~/toy2/analysis001/


# -----------------------------
# Plots
# -----------------------------
# metabolites to plot:
metabolites_to_plot:
  cell: ["Fructose_1,6-bisphosphate", # in "quotes" because has a comma inside
         L-Lactic_acid, Pyruvic_acid, L-Malic_acid,
         Fumaric_acid, L-Alanine, L-Glutamic_acid,
         L-Glutamine, L-Aspartic_acid]
  med:  [L-Lactic_acid, Pyruvic_acid, 
           L-Alanine, L-Asparagine]


# Abundances bars configuration
# -----------------------------
time_sel :
  - T0
  - T2h
barcolor : timepoint
axisx : condition
axisx_labeltilt : 20 # 0 is no tilt
width_each_subfig : 3
wspace_subfigs : 1

# Isotopologue Contribution plot configuration
# -----------------------------
width_each_stack : !!float 3
wspace_stacks : !!float 1.1
numbers_size : 13


# Fractional Contributions lineplot configuration
# -----------------------------
# will run with defaults, see --help 


# -----------------------------
# differential analysis
# -----------------------------
grouping :  # see explanation at the  end
  - condition
  - timepoint  

comparisons :   # for each pair,last must be control
  - [L-Cycloserine_T0, Control_T0]    
  - [L-Cycloserine_T2h, Control_T2h]          
              
statistical_test:
  abundances: prm-scipy  
  meanE_or_fracContrib: KW
  isotopologue_abs: null
  isotopologue_prop: KW
     
thresholds:
  padj: 0.2
  absolute_log2FC: 0


# grouping: column that is a combination of 2 metadata categories,
# new category thus generated, is ready for comparison. Example :
#  Control (a condition) combined with T0 (a timepoint), yields Control_T0
#  L-Cyclo (another condition) combined with T0 (same timepoint) yields L-Cyclo_T0
#  thus now, we are able to compare L-Cyclo_T0 against Control_T0 .

# -------------------- end of config file ---------------------         
# NOTE: Metabolograms need a separated configuration file
