# Note: for indentation use space (never tab!): 2 space indents
# coments start with #

# -----------------------------
# necesary to all steps
# -----------------------------

metadata_path : ~/toy3/data/metadata_toy3.csv 
targetedMetabo_path: ~/toy3/data/generic_toy3.xlsx 
amountMaterial_path : null # null or the file path, if available
typeprep : generic_prep

# when generic,  names of the sheets in xlsx file that exist (null otherwise) !!!!!
name_abundance : null
name_meanE_or_fracContrib : null
name_isotopologue_prop : null
name_isotopologue_abs : isotopologuesCorrValues  # isotopologue absolute values

conditions : [sgCont, sgLDHA] # first must be control, when several
suffix : toy3a01
out_path : ~/toy3/analysis01/


# -----------------------------
# Plots
# -----------------------------
metabolites_to_plot:
  endo: [a-KG, 2-OHGLu, 2_3-PG]
  exo: [2_3-PG, 2-OHGLu]

# Abundances bars configuration
# -----------------------------
time_sel : [T0, T2h]
axisx : condition
barcolor : timepoint
width_each_subfig : 3
wspace_subfigs : 1
axisx_labeltilt : 90 # 20 or another


# Isotopologue Contribution plot configuration
# -----------------------------
width_each_stack : !!float 2.8
wspace_stacks : !!float 1.1
numbers_size : 13

# Fractional Contributions lineplot configuration
# -----------------------------
# if defining groups, try to group them by similarity in values
# or leave blank as in  the other toy examples
groups_toplot_frac_contribs:
  endo:
    0: [ a-KG, 2-OHGLu]
    1: [ 6-PG, 2_3-PG]
  exo:
    0: [ 6-PG, 2_3-PG] 
    1: [ a-KG, 2-OHGLu]


# -----------------------------
# differential analysis
# -----------------------------
grouping : [condition, timepoint]  # see explanation at the file end

comparisons : 
  - [sgLDHA_T0, sgCont_T0]  # for each pair,last must be control
  - [sgLDHA_T24, sgLDHA_T0]             
  - [sgLDHA_T24, sgCont_T24]            
              
statistical_test:
  abundances: Tt   
  meanE_or_fracContrib: KW
  isotopologue_abs: KW 
  isotopologue_prop: null
     
thresholds:
  padj: 0.5
  absolute_log2FC: 0.7


# grouping: column that is a combination of 2 metadata categories,
# new category thus generated, is ready for comparison. Example :
#  Control (a condition) combined with T0 (a timepoint), yields Control_T0
#  L-Cyclo (another condition) combined with T0 (same timepoint) yields L-Cyclo_T0
#  thus now, we are able to compare L-Cyclo_T0 against Control_T0 .

# -------------------- end of config file ---------------------         
# NOTE: Metabolograms need a separated configuration file
